version: '2'
services:
  selenium:
    image: selenium/standalone-chrome:3.14.0-beryllium
    container_name: selenium
    shm_size: 2g
    ports:
      - 4444:4444
  codecept:
    build:
      context: ..
      dockerfile: docker/codecept.Dockerfile
    container_name: codeceptjs
    user: ${USER_ID}
    network_mode: host
    volumes:
     - ../:/tests
